PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX ch:<http://purl.obolibrary.org/obo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT distinct ?chebi WHERE {
  ?reaction rdfs:subClassOf rh:Reaction .  
#to get to GO xrefs use bi
  ?reaction rh:bidirectionalReaction ?rheaBi .
# get participants
  ?reaction rh:side ?reactionSide .
  ?reactionSide rh:contains ?participant .
  ?participant rh:compound ?compound .
  ?compound rh:name ?compoundLabel .  
# get chebi for participants
# gets typical small molecule participants
 optional{ ?compound rh:chebi ?chebi . } 
#gets generic compounds 
 optional{ 
   ?compound rh:reactivePart ?reactivePart . 
   ?reactivePart rh:chebi ?chebi }
#gets polymers 
   optional{ 
   ?compound rh:underlyingChebi ?chebi .
   ?compound rh:polymerizationIndex ?polymer_index}    
}