PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX ch:<http://purl.obolibrary.org/obo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT ?reaction ?reactionLabel ?EC ?rhea ?rheaBiAccession ?reactionSide ?compoundLabel ?stoich ?reactivePart ?polymer_index ?chebi WHERE {
  ?reaction rdfs:subClassOf rh:Reaction . 
  ?reaction rh:status rh:Approved .
  ?reaction rh:equation ?reactionLabel . 
  ?reaction rh:accession ?rhea .  
  #filter(?rhea = "RHEA:13573") . 
  #filter(?rhea = "RHEA:15389") .
#to get to GO xrefs use bi
  ?reaction rh:bidirectionalReaction ?rheaBi .
  ?rheaBi rh:accession ?rheaBiAccession . 
#  filter(?rheaBiAccession = "RHEA:24167") . 
# limit to reactions that have EC numbers 
optional {
  ?reaction rh:ec ?EC .
  }
# get participants
  ?reaction rh:side ?reactionSide .
  ?reactionSide rh:contains ?participant .
  ?reactionSide ?containsWithStoich ?participant . 
  ?containsWithStoich rh:coefficient ?stoich . 
  ?participant rh:compound ?compound .
  ?compound rh:name ?compoundLabel .  
# get chebi for participants
# gets typical small molecule participants
 optional{ ?compound rh:chebi ?chebi . } 
#gets generic compounds 
 optional{ 
   ?compound rh:reactivePart ?reactivePart . 
   ?reactivePart rh:chebi ?chebi }
#gets polymers 
   optional{ 
   ?compound rh:underlyingChebi ?chebi .
   ?compound rh:polymerizationIndex ?polymer_index}   
  
#and xrefs to directional reactions in other databases 
 # ?reaction rh:directionalReaction ?directionalReaction . 
 # ?directionalReaction rdfs:seeAlso ?xref . 
 # ?directionalReaction rh:substrates ?inputSide . 
 # ?directionalReaction rh:products ?outputSide . 
}
order by ?reaction ?reactionSide 
