prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix obo: <http://purl.obolibrary.org/obo/>
prefix providedBy: <http://purl.org/pav/providedBy> 
prefix evidence: <http://geneontology.org/lego/evidence> 
prefix dc: <http://purl.org/dc/elements/1.1/>

delete {
  ?anno_node evidence: ?value . 
  ?value ?prop2 ?value2 
} 
 where{
  ?reaction obo:BFO_0000050 ?pathway . 
  ?reaction rdf:type obo:GO_0003674 .
  ?pathway rdf:type obo:GO_0008150 .
  ?anno_node owl:annotatedSource ?pathway .
  ?anno_node owl:annotatedTarget ?reaction .
  ?anno_node owl:annotatedProperty obo:BFO_0000051  .
  ?anno_node evidence: ?value . 
  ?value ?prop2 ?value2 
  }