prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix obo: <http://purl.obolibrary.org/obo/>

delete {
  ?physical_entity obo:RO_0001025 ?location . 
  ?location rdf:type ?location_class .
 ## must also delete annotations added for these assertions 
  ?anno_node owl:annotatedProperty obo:RO_0001025 .
  ?anno_node ?prop ?c 
}
where {
  ?physical_entity rdf:type ?entity_class . 
  ?entity_class rdfs:subClassOf ?grouping_class .
  VALUES ?grouping_class { obo:GO_0032991 obo:CHEBI_36080 obo:BFO_0000002} .
  ?physical_entity obo:RO_0001025 ?location .
  ?location rdf:type ?location_class .
  ?anno_node owl:annotatedSource ?physical_entity .
  ?anno_node owl:annotatedTarget ?location .
}