prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix obo: <http://purl.obolibrary.org/obo/>
#prefix biopax: <http://www.biopax.org/release/biopax-level3.owl#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
#infer that an entity (either protein or protein complex) E enables a reaction R2
#if R1 provides direct input for R2 
#and R1 has output E1
#and R2 has input E2
#and E1 = E2
# and R2 is not enabled by anything else 
#delete { ?reaction2 obo:RO_0002233 ?input . 
 ## must also delete annotations added for these assertions 
#  ?anno_node owl:annotatedProperty obo:RO_0002233 .
 # ?anno_node ?prop ?c 
# }  
select ?reaction2 ?input ?reaction1   # for update
where {
 FILTER NOT EXISTS {
 	?reaction2 obo:RO_0002333 ?any_enabler 
 }
  { 	?reaction1 obo:RO_0002413 ?reaction2 .
  	?reaction1 rdf:type obo:GO_0003674 .
   	?reaction1 obo:RO_0002234 ?output .
   	?reaction2 rdf:type obo:GO_0003674 .
   	?reaction2 obo:RO_0002233 ?input . 
    	?output rdfs:label ?outputLabel .
  	?input rdfs:label ?inputLabel .
    ?input skos:exactMatch ?complex . 
    ?output skos:exactMatch ?complex . 
     ?input rdf:type obo:GO_0032991 .
    ?output rdf:type obo:GO_0032991 .
    } 
    UNION
   { ?reaction1 obo:RO_0002413 ?reaction2 .
  	?reaction1 rdf:type obo:GO_0003674 .
   	?reaction1 obo:RO_0002234 ?output .
   	?reaction2 rdf:type obo:GO_0003674 .
   	?reaction2 obo:RO_0002233 ?input . 
    	?output rdfs:label ?outputLabel .
  	?input rdfs:label ?inputLabel .
    ?input skos:exactMatch ?protein . 
    ?output skos:exactMatch ?protein . 
    ?input rdf:type ?uniprot . 
    ?output rdf:type ?uniprot .
   # ?uniprot rdfs:subClassOf biopax:Protein . 
   ?uniprot rdfs:subClassOf obo:CHEBI_36080 .
    } 

}

  #	?input rdf:type ?entity_class .  #at one point.. specific, new classes were created for ?entity_class like "TCF/LEF:CTNNB1" (which could be logically defined as an intersection of the proteins that make it up)
  #	?output rdf:type ?entity_class . 
  #	?entity_class rdfs:subClassOf ?grouping_class .
  #	VALUES ?grouping_class { obo:GO_0032991 biopax:Protein} # either protein complex or protein class
  
#filter(?outputLabel = ?inputLabel) .
#limit 100
# group by ?prop 
#ORDER BY DESC(?prop)

#limit 100
# group by ?prop 
# ORDER BY DESC(?prop)

# obo:RO_0002233 has input 
# obo:RO_0002333 enabled by
# RO_0002234 has output
# obo:BFO_0000051 has part
# obo:RO_0002413 provides direct input for